export const isocalciOptions = {
    employees: [
      "1-5",
      "6-10",
      "11-15",
      "16-25",
      "26-45",
      "45-65",
      "66-85",
      "86-125",
      "126-175",
      "176-275",
      "276-425",
      "426-625",
      "628-875",
      "876-1175",
      "1176-1550",
      "1551-2025",
      "2026-2675",
      "2676-3450",
      "3451-4350",
      "4351-5450",
      "5451-6800",
      "6801-8500",
      "8501-10700",
      "10700",
    ],
    locations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    countryScopes: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Comoros",
      "Congo",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Democratic Republic of the Congo",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "East Timor (Timor-Leste)",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Ivory Coast",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kosovo",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "North Macedonia (Macedonia)",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "North Korea",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russia",
      "Rwanda",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Korea",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "State of Palestine",
      "Sudan",
      "Suriname",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Togo",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Vatican City",
      "Venezuela",
      "Vietnam",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ],
    choiceOfStandards: [
      "ISO 27001",
      "ISO 27701",
      "ISO 22301",
      "ISO 20000",
      "ISO 9001",
    ],
  };
  
  export const auditTimeStages = {
    "1-5": 1.5,
    "6-10": 2,
    "11-15": 2.5,
    "16-25": 3,
    "26-45": 4,
    "45-65": 5,
    "66-85": 6,
    "86-125": 7,
    "126-175": 8,
    "176-275": 9,
    "276-425": 10,
    "426-625": 11,
    "628-875": 12,
    "876-1175": 13,
    "1176-1550": 14,
    "1551-2025": 15,
    "2026-2675": 16,
    "2676-3450": 17,
    "3451-4350": 18,
    "4351-5450": 19,
    "5451-6800": 20,
    "6801-8500": 21,
    "8501-10700": 22,
    10700: 23,
  };
  
  export const calculateAdditionalDays = (locations) => {
    if (locations === 1) return 0;
    return (locations - 1) * 3; // location value starts from 1 , when 3 x (location-1) = 0, 3x (location-2) = 3
  };
  export const calculatePerDayAuditFee = (country) => {
    if (saarcCountries.includes(country)) {
      return 15000; // INR for SAARC countries
    } else {
      return 1000; // USD for other countries
    }
  };
  
  export const calculateRegistrationFee = (country, standard) => {
    const registrationFeesIndia = {
      "ISO 27001": 65000,
      "ISO 27701": 65000,
      "ISO 22301": 65000,
      "ISO 20000": 65000,
      "ISO 9001": 25000,
    };
  
    const registrationFeesOthers = {
      "ISO 27001": 15000,
      "ISO 27701": 15000,
      "ISO 22301": 15000,
      "ISO 20000": 15000,
      "ISO 9001": 800,
    };
  
    if (saarcCountries.includes(country)) {
      return registrationFeesIndia[standard]; // INR for SAARC countries
    } else {
      return registrationFeesOthers[standard]; // USD for other countries
    }
  };
  export let saarcCountries = [
    "India",
    "Afghanistan",
    "Bangladesh",
    "Bhutan",
    "Maldives",
    "Nepal",
    "Pakistan",
    "Sri Lanka",
  ];
  
  export const style = {
    position: "fixed",
  
    transform: "translate(0%, 50%)",
    width: 500,
    bgcolor: "background.paper",
    // boxShadow: 24,
    p: 4, //padding
  
  
  };
  
  
   export const handleEmployeeChange = (event) => {
     setEmployeeOption(event.target.value);
   };
  
   export const handleLocationChange = (event) => {
     setLocationOption(parseInt(event.target.value, 10));
   };
  
   export const handleCountryScopeChange = (event) => {
     setCountryOption(event.target.value);
   };
  
   export const handleChoiceOfStandardChange = (event) => {
     setStandardOption(event.target.value);
   };
  
  